### ISSUE TITLE
InterceptAlert default value

### ISSUE THREAD

**Issue by Evanito** [Hafas/indiegala-auto-enter#2]
Hey Hafas, 
From my understanding the `interceptAlert` setting is very useful for automating usage of the bot, so shouldn't it be enabled by default.

**Comment by Hafas** [comment]
I was considering to enable it by default, but after some thought I decided it would be more responsible to let the user set this option actively to `true` since I don't know if the alerts may contain some useful information.

This way the alerts only disappear when the user has read the docs and know the consequences of this option.
