### ISSUE TITLE
joinOwnedGames field?

### ISSUE THREAD

**Issue by zypA13510** [Hafas/indiegala-auto-enter#6]
It looks like joinOwnedGames field is no longer used after commit 8b6c3803f84845a0dc8251763ab2644362065f2d. Any idea to bring it back, or to remove it from the documentation?

**Comment by Hafas** [comment]
I removed it, when I realized that IndieGala doesn't let you join owned games anyway. Removed from documentation.

**Comment by zypA13510** [comment]
Are you sure? Because it seems that I can join them on my end.
![image](https://cloud.githubusercontent.com/assets/8077540/21712836/cda3477c-d431-11e6-934c-e836c82e8670.png)
![image](https://cloud.githubusercontent.com/assets/8077540/21712843/d2bc802a-d431-11e6-91fd-1ba51853d067.png)

That's why I made a temporary patch on my fork, zypA13510/indiegala-auto-enter@ef650644986563bebddbe9e1c45861ccd58da6da

**Comment by Hafas** [comment]
I'm sure that this was the case, when I removed the option from the code a couple months ago. You got a "duplicate" message in your payload.
But I just tested it again, and you're right: You can now enter giveaways of owned games. I think it's a bug in IndieGala's end though because in the details page of these giveaways the tickets are greyed out, indicating you can't enter the giveaway.

I'll reinsert the removed code in a couple minutes.

**Comment by Hafas** [comment]
readded `joinOwnedGames` https://github.com/Hafas/indiegala-auto-enter/commit/e47ba3c881d43ed9be1db2203913b7381ad014ad

Thank you for your contribution.
